name: Coverage
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.7'
          cache: 'pip'
      - run: python -m pip install -r requirements.txt
      - uses: ./.github/actions/coverage
        with:
          html_report_name: coverage-linux
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'
      - uses: actions/cache/restore@v4
        id: restore_cache
        with:
          path: libsodium.dll
          key: cache_libsodium_dll
      - run: python -m pip install -r requirements.txt
      - uses: ./.github/actions/coverage
        with:
          html_report_name: coverage-windows
      - uses: actions/cache/save@v4
        if: steps.restore_cache.outputs.cache-hit != 'true'
        with:
          path: libsodium.dll
          key: cache_libsodium_dll
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: python -m pip install -r requirements.txt
      - uses: ./.github/actions/coverage
        with:
          html_report_name: coverage-macos
