name: Mypy
on: [pull_request, workflow_dispatch]
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: mypy -p ipv8
