name: Mypy
on: [pull_request, workflow_dispatch]
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python -m pip install -r requirements.txt
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: mypy --install-types --non-interactive
